# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Duke's Journal 
tagline:          Learning through doing
description:      "Duke's journal is about reflecting on coaching lessons so that we can develop better outcomes."
url:              sarahfeng.com
baseurl:          /

author:
  name:           'elizabeth zhiying feng'
  url:            sarahfeng.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           sarahfeng
