# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Duke's Journal 
tagline:          Learning through doing
description:      "Duke's journal is about reflecting on coaching lessons so that we can develop better outcomes."
url:              dukejournal.github.io
baseurl:          /

author:
  name:           'Duke'
  url:            http://dukejournal.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://dukejournal.github.io
