# site
title: elizabeth zhiying feng
baseurl: ""
url: "http://sarahfeng.com"
favicon: "/assets/feng.png"

# bio
header: elizabeth zhiying feng<br>
    冯稚颖
desc: >
    visual artist, researcher, writer, and code monkey based out of berkeley
    recipient of a 2021 poetry & the senses fellowship from uc berkeley's arts research center
  
# posts
date_format: "%Y"
post_title: Work
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
