# site
title: elizabeth zhiying feng
baseurl: ""
url: "http://sarahfeng.com"
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: (sarah) elizabeth zhiying feng
desc: >
visual artist, writer, and code monkey based out of berkeley 
> i run a [music blog](musicalculinarists.github.io), tooo
  
  

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
