# site
title: elizabeth zhiying feng
baseurl: ""
url: "http://sarahfeng.com"
favicon: "/assets/feng.png"
g_analytics: UA-12345678-1

# bio
header: "(sarah) elizabeth zhiying feng\n
    冯稚颖\n"
desc: >
    visual artist, writer, and code monkey based out of berkeley
  
  

# posts
date_format: "%Y"
post_title: Story
post_date: Year
post_cat: Genre

# post detail
prev-next: true

# build settings
markdown: kramdown
theme: louie
exclude:
  - Gemfile
  - Gemfile.lock
